SPX-314: [acume] java.lang.NoSuchMethodError because of multiple version of guava in acume war.
Former-commit-id: 0534c547f543d91f9206f1c64955be2736a72100