SPX-314: [acume] java.lang.NoSuchMethodError because of multiple version of guava in acume war.
Former-commit-id: 6e246b7cd5b79469fb83634d67767f237653ceff